#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Code-Wiki generation: the stable symbol index Markdown file.

Reads the RAG database and renders `doc/code_wiki.md` (file -> symbols with
signature/docstring/lines, cross-file usages, per-language dependencies).
Depends on a `ProjectRAG` storage instance from `db`.
"""

import json
import os
import re
from contextlib import closing


def _wiki_anchor(path: str) -> str:
    """Build a GitHub-style Markdown anchor from a file path."""
    base = os.path.splitext(os.path.basename(path))[0].lower()
    return re.sub(r"[^a-z0-9]+", "-", base).strip("-")


def _file_dependencies(conn, file_path: str, language: str) -> list:
    """Collect imports/#includes of a file from the module chunks."""
    if language == "markdown":
        return []
    rows = conn.execute(
        "SELECT content FROM code_chunks WHERE file_path = ? AND symbol_type = 'module'",
        (file_path,),
    ).fetchall()
    deps = []
    seen = set()
    for r in rows:
        for line in r["content"].splitlines():
            line = line.strip()
            is_dep = (
                language == "python" and (line.startswith("import ") or line.startswith("from "))
            ) or (
                language == "cpp" and line.startswith("#include")
            )
            if is_dep and line not in seen:
                seen.add(line)
                deps.append(line)
            if len(deps) >= 60:
                return deps
    return deps


def _find_usages(conn, symbol_name: str, file_path: str) -> list:
    """Find usages of a symbol in the content of other chunks.

    Checks whether `symbol_name` occurs as a whole word in the content
    of chunks from other files (= `used_by` relationship).
    Returns a list of (file_path, line_start, symbol_type, chunk_id).
    """
    if not symbol_name or len(symbol_name) < 3:
        return []
    rows = conn.execute(
        """
        SELECT DISTINCT c.file_path, c.line_start, c.symbol_type, c.chunk_id
        FROM code_chunks c
        WHERE c.file_path != ?
          AND c.chunk_id IS NOT NULL
          AND c.content LIKE ?
        LIMIT 20
        """,
        (file_path, f"%{symbol_name}%"),
    ).fetchall()
    # Post-filter on whole words (no substring hits like "init" in "initialized")
    pattern = re.compile(r"(?<!\w)" + re.escape(symbol_name) + r"(?!\w)")
    result = []
    seen = set()
    for r in rows:
        key = (r["file_path"], r["line_start"])
        if key in seen:
            continue
        seen.add(key)
        # Fetch the content for verification
        chunk = conn.execute(
            "SELECT content FROM code_chunks WHERE chunk_id = ?",
            (r["chunk_id"],),
        ).fetchone()
        if chunk and pattern.search(chunk["content"]):
            result.append(dict(r))
    return result[:10]


def generate_wiki(rag, wiki_path: str) -> dict:
    """Generate the Code-Wiki (stable symbol index) as a Markdown file."""
    with closing(rag._connect()) as conn:
        files = conn.execute(
            "SELECT DISTINCT file_path, language FROM code_chunks ORDER BY file_path"
        ).fetchall()
        n_chunks = conn.execute("SELECT COUNT(*) AS n FROM code_chunks").fetchone()["n"]
        n_syms = conn.execute(
            "SELECT COUNT(*) AS n FROM code_chunks WHERE symbol_name IS NOT NULL"
        ).fetchone()["n"]

        out = [
            "# wogd-ddsp-trainer Code-Wiki",
            "",
            "_Automatically generated symbol index. Complements "
            "[`doc/architecture.md`](./architecture.md) - manually "
            "maintained architecture knowledge (DDSP model graph, dataset "
            "pipeline, training loop, web UI). See also "
            "[`doc/index.md`](./index.md) for the LLM-Wiki knowledge catalog "
            "and [`doc/log.md`](./log.md) for the chronological changelog._",
            "",
            "<!-- AUTOGENERATED_WIKI_START -->",
            "",
            f"_Automatically generated by `index_project_code` (MCP server). "
            f"{len(files)} files, {n_chunks} chunks, {n_syms} symbols._",
            "",
            "This wiki is the structured symbol index of the codebase. Coding "
            "agents read it once per session as stable context (prompt-cache "
            "friendly) and always verify details against the real source code "
            "(path + line numbers).",
            "",
            "## Table of contents",
        ]
        for f in files:
            out.append(f"- [`{f['file_path']}`](#{_wiki_anchor(f['file_path'])})")
        out.append("")

        for f in files:
            out.append(f"## {f['file_path']}")
            out.append("")
            out.append(f"- Language: `{f['language']}`")
            # Frontmatter metadata for Markdown concept files (LLM-Wiki/OKF)
            if f["language"] == "markdown":
                fm_row = conn.execute(
                    "SELECT frontmatter FROM code_chunks "
                    "WHERE file_path = ? AND symbol_type = 'frontmatter' "
                    "LIMIT 1",
                    (f["file_path"],),
                ).fetchone()
                if fm_row and fm_row["frontmatter"]:
                    try:
                        fm = json.loads(fm_row["frontmatter"])
                        out.append(f"- Type: `{fm.get('type', '?')}`")
                        out.append(f"- Status: `{fm.get('status', '?')}`")
                        if fm.get("stale_after"):
                            out.append(f"- Stale after: `{fm['stale_after']}`")
                        if fm.get("description"):
                            out.append(f"- Description: {fm['description'][:160]}")
                        if fm.get("generated") and isinstance(fm["generated"], dict):
                            out.append(f"- Generated: {fm['generated'].get('by', '?')} @ {fm['generated'].get('at', '?')}")
                    except (json.JSONDecodeError, KeyError):
                        pass
            deps = _file_dependencies(conn, f["file_path"], f["language"])
            if deps:
                out.append("- Dependencies: " + ", ".join(deps))
            syms = conn.execute(
                """
                SELECT symbol_type, symbol_name, signature, docstring,
                       line_start, line_end
                FROM code_chunks
                WHERE file_path = ? AND symbol_name IS NOT NULL
                ORDER BY line_start
                """,
                (f["file_path"],),
            ).fetchall()
            out.append("")
            if not syms:
                out.append("(no named symbols - only text/Markdown)")
            else:
                out.append("Symbols:")
                for s in syms:
                    kind = s["symbol_type"] or ""
                    sig = (s["signature"] or "").replace("|", "\\|")
                    doc_lines = (s["docstring"] or "").strip().splitlines()
                    doc1 = doc_lines[0][:120] if doc_lines else ""
                    entry = (
                        f"- `{s['symbol_name']}` ({kind}, "
                        f"lines {s['line_start']}-{s['line_end']}) - {sig}"
                    )
                    if doc1:
                        entry += f" - {doc1}"
                    out.append(entry)
                    # used_by: symbols from other files that reference this one
                    used_by = _find_usages(conn, s["symbol_name"], f["file_path"])
                    if used_by:
                        for u in used_by:
                            out.append(
                                f"  - *used by* `{u['file_path']}:{u['line_start']}` "
                                f"({u['symbol_type'] or '?'}) [{u['chunk_id']}]"
                            )
            out.append("")

    out_dir = os.path.dirname(os.path.abspath(wiki_path))
    os.makedirs(out_dir, exist_ok=True)
    with open(wiki_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    return {"path": wiki_path, "files": len(files), "chunks": n_chunks, "symbols": n_syms}
